using FluentValidation;
using Microsoft.EntityFrameworkCore;
using Prime.Application.Common;
using Prime.Application.Common.Interfaces;
using Prime.Application.Features.Numbering;
using Prime.Application.Features.PropertyIdentification;
using Prime.Domain.DomainServices;
using Prime.Domain.Entities;
using Prime.Domain.Enums;

namespace Prime.Application.Features.Properties;

public sealed class PropertyService(IApplicationDbContext db, IValidator<CreatePropertyRequest> validator, INumberingService numbering, IClock clock) : IPropertyService
{
    public async Task<Result<PropertyDto>> CreateAsync(CreatePropertyRequest request, CancellationToken cancellationToken = default)
    {
        var validation = await validator.ValidateAsync(request, cancellationToken);
        if (!validation.IsValid)
        {
            return Result.Failure<PropertyDto>("VALIDATION_FAILED", string.Join("; ", validation.Errors.Select(e => e.ErrorMessage)));
        }

        if (!await db.Provinces.AnyAsync(x => x.Id == request.ProvinceId, cancellationToken))
        {
            return Result.Failure<PropertyDto>("PROVINCE_NOT_FOUND", "The specified province does not exist.");
        }
        if (!await db.Municipalities.AnyAsync(x => x.Id == request.MunicipalityId && x.ProvinceId == request.ProvinceId, cancellationToken))
        {
            return Result.Failure<PropertyDto>("MUNICIPALITY_NOT_FOUND", "The specified municipality does not exist within the specified province.");
        }
        if (!await db.Barangays.AnyAsync(x => x.Id == request.BarangayId && x.MunicipalityId == request.MunicipalityId, cancellationToken))
        {
            return Result.Failure<PropertyDto>("BARANGAY_NOT_FOUND", "The specified barangay does not exist within the specified municipality.");
        }
        if (request.ZoneId is not null && !await db.Zones.AnyAsync(x => x.Id == request.ZoneId, cancellationToken))
        {
            return Result.Failure<PropertyDto>("ZONE_NOT_FOUND", "The specified zone does not exist.");
        }

        // The PIN is typed, or generated by the PIN numbering scheme in force
        // (docs/FORMS-REVISION-PLAN.md section 4.4); generation and save are one transaction.
        var today = clock.Today;
        var ownsTransaction = db.Database.CurrentTransaction is null;
        await using var transaction = ownsTransaction ? await db.Database.BeginTransactionAsync(cancellationToken) : null;
        // A PIN scheme built on the tax map section ({SECT}) cannot number a property before it
        // is mapped (docs/analysis/property-identification.md, decision 4): the property then gets a
        // typed PIN or a temporary one, and its permanent PIN when its parcel is placed in a section.
        var context = await PinContexts.ForBarangayAsync(db, request.BarangayId, today.Year, sectionIndex: null, cancellationToken);
        var scheme = await db.NumberingSchemes.InForce(today)
            .FirstOrDefaultAsync(x => x.AppliesTo == NumberedDocumentKind.PropertyIdentificationNumber, cancellationToken);
        var sectioned = scheme is not null && NumberPattern.Tokens(scheme.Pattern).Contains("SECT");
        var typed = string.IsNullOrWhiteSpace(request.PropertyIdentificationNumber) ? null : request.PropertyIdentificationNumber;
        var kind = PinKind.Registered;
        Result<string> pin;
        if (sectioned && typed is null)
        {
            kind = PinKind.Temporary;
            var temporary = await numbering.GenerateIfConfiguredAsync(NumberedDocumentKind.TemporaryPin, context, today, cancellationToken);
            pin = temporary.IsFailure ? Result.Failure<string>(temporary.Code!, temporary.Message!)
                : temporary.Value is { } value ? Result.Success(value)
                : Result.Failure<string>("NUMBER_REQUIRED",
                    "The permanent PIN is given when the parcel is placed in a tax map section. Type a PIN, or configure a TemporaryPin numbering scheme.");
        }
        else
        {
            // Typed (checked against the scheme's manual-entry rules, e.g. for migration) or generated by a scheme without a section.
            pin = await numbering.AssignAsync(NumberedDocumentKind.PropertyIdentificationNumber, context, typed, today, cancellationToken);
        }
        if (pin.IsFailure)
        {
            return Result.Failure<PropertyDto>(pin.Code!, pin.Message!);
        }
        if (await db.Properties.AnyAsync(p => p.PropertyIdentificationNumber == pin.Value, cancellationToken)
            || await db.PinAssignments.AnyAsync(p => p.Pin == pin.Value, cancellationToken))
        {
            return Result.Failure<PropertyDto>("PROPERTY_PIN_DUPLICATE", $"PIN '{pin.Value}' has already been given; PINs are never reused.");
        }

        var property = new PropertyEntity
        {
            PropertyIdentificationNumber = pin.Value,
            ProvinceId = request.ProvinceId,
            MunicipalityId = request.MunicipalityId,
            BarangayId = request.BarangayId,
            ZoneId = request.ZoneId,
            Street = request.Street,
            Sitio = request.Sitio,
            LotNumber = request.LotNumber,
            BlockNumber = request.BlockNumber,
            SurveyNumber = request.SurveyNumber,
            TitleNumber = request.TitleNumber,
            TaxMapNumber = request.TaxMapNumber,
            Status = RecordStatus.Active,
        };

        db.Properties.Add(property);
        db.PinAssignments.Add(new Prime.Domain.Entities.PinAssignment
        {
            Property = property, Pin = pin.Value, Kind = kind, AssignedAt = clock.UtcNow,
        });
        await db.SaveChangesAsync(cancellationToken);
        if (transaction is not null)
        {
            await transaction.CommitAsync(cancellationToken);
        }

        return Result.Success(await MapToDto(property.Id, cancellationToken)
            ?? throw new InvalidOperationException("Property was just created but could not be reloaded."));
    }

    public async Task<Result<PropertyProfileDto>> GetProfileAsync(Guid propertyId, CancellationToken cancellationToken = default)
    {
        var property = await MapToDto(propertyId, cancellationToken);
        if (property is null)
        {
            return Result.Failure<PropertyProfileDto>("PROPERTY_NOT_FOUND", "No property was found with the given id.");
        }

        var owners = await PropertyParties.ProjectAsync(db.PropertyTaxpayers.Where(pt => pt.PropertyId == propertyId), cancellationToken);

        var parcels = await db.Parcels
            .Where(p => p.PropertyId == propertyId)
            .Select(p => new ParcelSummaryDto(p.Id, p.Area, p.LotNumber, p.Barangay!.Name, p.Status, p.BarangayId, p.Section!.IndexNumber, p.ParcelNumber))
            .ToListAsync(cancellationToken);

        var rpus = await db.RealPropertyUnits
            .Where(r => r.PropertyId == propertyId)
            .OrderByDescending(r => r.EffectivityDate)
            .Select(r => new RpuSummaryDto(r.Id, r.RpuNumber, r.RpuType, r.Status, r.EffectivityDate))
            .ToListAsync(cancellationToken);

        var taxDeclarations = await db.TaxDeclarations
            .Where(td => td.PropertyId == propertyId)
            .OrderByDescending(td => td.EffectivityDate)
            .Select(td => new TaxDeclarationSummaryDto(td.Id, td.TaxDeclarationNumber, td.RevisionNumber, td.AssessmentYear, td.Status, td.EffectivityDate))
            .ToListAsync(cancellationToken);

        return Result.Success(new PropertyProfileDto(property, owners, parcels, rpus, taxDeclarations));
    }

    public async Task<Result<PagedResult<PropertyDto>>> SearchAsync(PropertySearchRequest request, CancellationToken cancellationToken = default)
    {
        var query = db.Properties.AsQueryable();

        if (!string.IsNullOrWhiteSpace(request.SearchTerm))
        {
            // .ToLower().Contains() (not EF.Functions.ILike) deliberately —
            // keeps Application decoupled from the Npgsql-specific
            // provider; translates to a portable case-insensitive LIKE.
            var term = request.SearchTerm.Trim().ToLower();
            query = query.Where(p =>
                p.PropertyIdentificationNumber.ToLower().Contains(term) ||
                (p.LotNumber != null && p.LotNumber.ToLower().Contains(term)) ||
                (p.TitleNumber != null && p.TitleNumber.ToLower().Contains(term)) ||
                (p.SurveyNumber != null && p.SurveyNumber.ToLower().Contains(term)) ||
                (p.TaxMapNumber != null && p.TaxMapNumber.ToLower().Contains(term)));
        }

        if (request.BarangayId is not null)
        {
            query = query.Where(p => p.BarangayId == request.BarangayId);
        }
        if (request.MunicipalityId is not null)
        {
            query = query.Where(p => p.MunicipalityId == request.MunicipalityId);
        }

        var totalCount = await query.CountAsync(cancellationToken);

        var entities = await IncludeReferences(query)
            .OrderBy(p => p.PropertyIdentificationNumber)
            .Skip((request.Page - 1) * request.PageSize)
            .Take(request.PageSize)
            .ToListAsync(cancellationToken);
        var items = entities.Select(ProjectToDto).ToList();

        return Result.Success(new PagedResult<PropertyDto>
        {
            Items = items,
            TotalCount = totalCount,
            Page = request.Page,
            PageSize = request.PageSize,
        });
    }

    // .Include() is required here even though ProjectToDto only reads
    // navigation properties (Province/Municipality/Barangay/Zone): EF Core
    // cannot translate a call to a separately-defined method inside
    // Select() into SQL, so it silently falls back to loading the raw
    // entity and invoking the method client-side — without Include, the
    // navigation properties are null and ProjectToDto throws a
    // NullReferenceException (found by actually running this against a
    // real database, not assumed).
    private async Task<PropertyDto?> MapToDto(Guid propertyId, CancellationToken cancellationToken)
    {
        var property = await IncludeReferences(db.Properties).SingleOrDefaultAsync(p => p.Id == propertyId, cancellationToken);
        return property is null ? null : ProjectToDto(property);
    }

    private static IQueryable<PropertyEntity> IncludeReferences(IQueryable<PropertyEntity> query) => query
        .Include(p => p.Province)
        .Include(p => p.Municipality)
        .Include(p => p.Barangay)
        .Include(p => p.Zone)
        .Include(p => p.TitleType);

    private static PropertyDto ProjectToDto(PropertyEntity p) => new(
        p.Id,
        p.PropertyIdentificationNumber,
        p.ProvinceId,
        p.Province!.Name,
        p.MunicipalityId,
        p.Municipality!.Name,
        p.BarangayId,
        p.Barangay!.Name,
        p.ZoneId,
        p.Zone == null ? null : p.Zone.Name,
        p.Street,
        p.Sitio,
        p.LotNumber,
        p.BlockNumber,
        p.SurveyNumber,
        p.TitleNumber,
        p.TaxMapNumber,
        p.Status,
        p.CreatedAt,
        p.TitleTypeId,
        p.TitleType == null ? null : p.TitleType.Name,
        p.TitleDate,
        p.BoundaryNorth,
        p.BoundaryEast,
        p.BoundarySouth,
        p.BoundaryWest);
}
