using FluentValidation;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Prime.Application.Common;
using Prime.Application.Common.Interfaces;
using Prime.Application.Features.Approvals;
using Prime.Application.Features.Numbering;
using Prime.Domain.Entities;
using Prime.Domain.Enums;

namespace Prime.Application.Features.TaxDeclarations;

public sealed class TaxDeclarationService(IApplicationDbContext db, IValidator<CreateTaxDeclarationRequest> validator, INumberingService numbering, IClock clock,
    ICurrentUserService currentUser, IApprovalChainService approvals, IOptions<FaasOptions> faas) : ITaxDeclarationService
{
    public async Task<Result<TaxDeclarationDto>> CreateAsync(CreateTaxDeclarationRequest request, CancellationToken cancellationToken = default)
    {
        var validation = await validator.ValidateAsync(request, cancellationToken);
        if (!validation.IsValid)
        {
            return Result.Failure<TaxDeclarationDto>("VALIDATION_FAILED", string.Join("; ", validation.Errors.Select(e => e.ErrorMessage)));
        }

        var rpu = await db.RealPropertyUnits.FirstOrDefaultAsync(r => r.Id == request.RpuId, cancellationToken);
        if (rpu is null)
        {
            return Result.Failure<TaxDeclarationDto>("RPU_NOT_FOUND", "No RPU was found with the given id.");
        }
        if (request.PropertyTransactionId is { } transactionId)
        {
            var tx = await db.PropertyTransactions.Include(x => x.RelatedProperties)
                .FirstOrDefaultAsync(x => x.Id == transactionId, cancellationToken);
            if (tx is null)
            {
                return Result.Failure<TaxDeclarationDto>("PROPERTY_TRANSACTION_NOT_FOUND", "The specified property transaction does not exist.");
            }
            if (tx.Status != WorkflowStatus.Draft)
            {
                return Result.Failure<TaxDeclarationDto>("PROPERTY_TRANSACTION_NOT_DRAFT", "TDs can be added only while the transaction is a Draft.");
            }
            if (tx.PropertyId != rpu.PropertyId && tx.RelatedProperties.All(r => r.PropertyId != rpu.PropertyId))
            {
                return Result.Failure<TaxDeclarationDto>("PROPERTY_TRANSACTION_OTHER_PROPERTY",
                    "The RPU's property is not the transaction's property or one of its related properties.");
            }
        }
        if (!await db.Classifications.AnyAsync(x => x.Id == request.ClassificationId, cancellationToken))
        {
            return Result.Failure<TaxDeclarationDto>("CLASSIFICATION_NOT_FOUND", "The specified classification does not exist.");
        }
        if (!await db.ActualUses.AnyAsync(x => x.Id == request.ActualUseId, cancellationToken))
        {
            return Result.Failure<TaxDeclarationDto>("ACTUAL_USE_NOT_FOUND", "The specified actual use does not exist.");
        }

        var revisionNumber = 1;
        if (request.PreviousTaxDeclarationId is not null)
        {
            var previous = await db.TaxDeclarations.FirstOrDefaultAsync(td => td.Id == request.PreviousTaxDeclarationId, cancellationToken);
            if (previous is null)
            {
                return Result.Failure<TaxDeclarationDto>("PREVIOUS_TAX_DECLARATION_NOT_FOUND", "The specified previous Tax Declaration does not exist.");
            }
            if (previous.RpuId != request.RpuId)
            {
                return Result.Failure<TaxDeclarationDto>("PREVIOUS_TAX_DECLARATION_OTHER_RPU", "The previous Tax Declaration belongs to a different RPU.");
            }
            if (previous.Status is WorkflowStatus.Cancelled or WorkflowStatus.Voided)
            {
                return Result.Failure<TaxDeclarationDto>("PREVIOUS_TAX_DECLARATION_CANCELLED",
                    $"TD {previous.TaxDeclarationNumber} is already cancelled; name the current TD instead.");
            }
            revisionNumber = previous.RevisionNumber + 1;
        }

        // The assessment this TD declares (the TD with it is the FAAS): named, or the one in force.
        var assessmentId = request.AssessmentId;
        if (assessmentId is { } named)
        {
            if (await FaasTaxDeclarations.AssessmentProblemAsync(db, request.RpuId, named, cancellationToken) is { } problem)
            {
                return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_ASSESSMENT_INVALID", problem);
            }
        }
        else
        {
            assessmentId = await FaasTaxDeclarations.AssessmentInForceAsync(db, request.RpuId, request.EffectivityDate, cancellationToken);
        }

        // Typed, or generated by the TD numbering scheme in force ({YEAR} = the
        // effectivity year); docs/FORMS-REVISION-PLAN.md section 4.4.
        var today = clock.Today;
        var ownsTransaction = db.Database.CurrentTransaction is null;
        await using var transaction = ownsTransaction ? await db.Database.BeginTransactionAsync(cancellationToken) : null;
        var context = await NumberContexts.ForPropertyAsync(db, rpu.PropertyId, request.EffectivityDate.Year, cancellationToken);
        var number = await numbering.AssignAsync(NumberedDocumentKind.TaxDeclaration, context, request.TaxDeclarationNumber, today, cancellationToken);
        if (number.IsFailure)
        {
            return Result.Failure<TaxDeclarationDto>(number.Code!, number.Message!);
        }
        if (await db.TaxDeclarations.AnyAsync(td => td.TaxDeclarationNumber == number.Value, cancellationToken))
        {
            return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NUMBER_DUPLICATE", $"A Tax Declaration with number '{number.Value}' already exists.");
        }

        var taxDeclaration = new TaxDeclaration
        {
            RpuId = request.RpuId,
            PropertyId = rpu.PropertyId,
            TaxDeclarationNumber = number.Value,
            RevisionNumber = revisionNumber,
            EffectivityDate = request.EffectivityDate,
            Taxability = request.Taxability,
            ClassificationId = request.ClassificationId,
            ActualUseId = request.ActualUseId,
            SubClassificationId = request.SubClassificationId,
            AssessmentYear = request.AssessmentYear,
            PreviousTaxDeclarationId = request.PreviousTaxDeclarationId,
            Remarks = request.Remarks,
            PropertyTransactionId = request.PropertyTransactionId,
            AssessmentId = assessmentId,
            Status = WorkflowStatus.Draft,
        };

        db.TaxDeclarations.Add(taxDeclaration);
        await db.SaveChangesAsync(cancellationToken);
        if (transaction is not null)
        {
            await transaction.CommitAsync(cancellationToken);
        }

        return Result.Success(await MapToDto(taxDeclaration.Id, cancellationToken)
            ?? throw new InvalidOperationException("Tax Declaration was just created but could not be reloaded."));
    }

    public async Task<Result<TaxDeclarationDto>> GetByIdAsync(Guid taxDeclarationId, CancellationToken cancellationToken = default)
    {
        var dto = await MapToDto(taxDeclarationId, cancellationToken);
        return dto is null
            ? Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NOT_FOUND", "No Tax Declaration was found with the given id.")
            : Result.Success(dto);
    }

    public async Task<Result<IReadOnlyList<TaxDeclarationDto>>> ListByRpuAsync(Guid rpuId, CancellationToken cancellationToken = default)
    {
        var entities = await IncludeReferences(db.TaxDeclarations)
            .Where(td => td.RpuId == rpuId)
            .OrderByDescending(td => td.RevisionNumber)
            .ToListAsync(cancellationToken);

        return Result.Success<IReadOnlyList<TaxDeclarationDto>>(entities.Select(ProjectToDto).ToList());
    }

    // .Include() required — see the identical comment in PropertyService.MapToDto.
    private async Task<TaxDeclarationDto?> MapToDto(Guid id, CancellationToken cancellationToken)
    {
        var entity = await IncludeReferences(db.TaxDeclarations).SingleOrDefaultAsync(td => td.Id == id, cancellationToken);
        return entity is null ? null : ProjectToDto(entity);
    }

    public async Task<Result<TaxDeclarationDto>> SubmitForReviewAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var td = await db.TaxDeclarations.FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (td is null)
        {
            return NotFound();
        }
        if (td.PropertyTransactionId is not null)
        {
            return InTransaction();
        }
        if (td.Status != WorkflowStatus.Draft)
        {
            return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NOT_DRAFT", "Only a Draft Tax Declaration can be submitted for review.");
        }
        td.Status = WorkflowStatus.PendingReview;
        await db.SaveChangesAsync(cancellationToken);
        return Result.Success((await MapToDto(id, cancellationToken))!);
    }

    public async Task<Result<TaxDeclarationDto>> ApproveAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var td = await db.TaxDeclarations.FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (td is null)
        {
            return NotFound();
        }
        if (td.PropertyTransactionId is not null)
        {
            return InTransaction();
        }
        if (td.Status != WorkflowStatus.PendingReview)
        {
            return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NOT_PENDING_REVIEW", "Only a Tax Declaration pending review can be approved.");
        }

        var step = await approvals.SignNextStepAsync(ApprovalSubjectType.TaxDeclaration, td.Id, td.CreatedBy, clock.Today, null, cancellationToken);
        if (step.IsFailure)
        {
            return Result.Failure<TaxDeclarationDto>(step.Code!, step.Message!);
        }
        if (!step.Value.ChainInForce && currentUser.AppUserId is not null && td.CreatedBy == currentUser.AppUserId)
        {
            return Result.Failure<TaxDeclarationDto>("CANNOT_APPROVE_OWN_TAX_DECLARATION", "The Tax Declaration's creator cannot also approve it (CLAUDE.md §46).");
        }
        var completes = !step.Value.ChainInForce || step.Value.Completed;

        TaxDeclaration? previous = null;
        if (completes)
        {
            var check = await TaxDeclarationApproval.CheckAsync(db, td, faas.Value.RequireAssessmentOnTd, cancellationToken);
            if (check.IsFailure)
            {
                return Result.Failure<TaxDeclarationDto>(check.Code!, check.Message!);
            }
            previous = check.Value;
        }

        var ownsTransaction = db.Database.CurrentTransaction is null;
        var transaction = ownsTransaction ? await db.Database.BeginTransactionAsync(cancellationToken) : null;
        try
        {
            if (completes)
            {
                await TaxDeclarationApproval.ApplyAsync(db, td, previous, currentUser.AppUserId, clock.UtcNow, cancellationToken);
            }
            else
            {
                await db.SaveChangesAsync(cancellationToken); // the signed step
            }
            if (transaction is not null)
            {
                await transaction.CommitAsync(cancellationToken);
            }
        }
        catch (DbUpdateException)
        {
            return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_APPROVAL_CONFLICT",
                "Another approval for this RPU happened at the same time. Nothing was changed; reload and try again.");
        }
        finally
        {
            if (transaction is not null)
            {
                await transaction.DisposeAsync();
            }
        }
        return Result.Success((await MapToDto(id, cancellationToken))!);
    }

    public async Task<Result<TaxDeclarationDto>> RejectAsync(Guid id, string reason, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(reason) || reason.Length > 1000)
        {
            return Result.Failure<TaxDeclarationDto>("VALIDATION_FAILED", "A reason is required (max 1000).");
        }
        var td = await db.TaxDeclarations.FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (td is null)
        {
            return NotFound();
        }
        if (td.PropertyTransactionId is not null)
        {
            return InTransaction();
        }
        if (td.Status != WorkflowStatus.PendingReview)
        {
            return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NOT_PENDING_REVIEW", "Only a Tax Declaration pending review can be rejected.");
        }
        td.Status = WorkflowStatus.Rejected;
        td.CancellationReason = reason;
        currentUser.Reason = reason;
        await db.SaveChangesAsync(cancellationToken);
        return Result.Success((await MapToDto(id, cancellationToken))!);
    }

    public async Task<Result<TaxDeclarationDto>> CancelAsync(Guid id, string reason, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(reason) || reason.Length > 1000)
        {
            return Result.Failure<TaxDeclarationDto>("VALIDATION_FAILED", "A reason is required (max 1000).");
        }
        var td = await db.TaxDeclarations.FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (td is null)
        {
            return NotFound();
        }
        if (td.Status != WorkflowStatus.Approved)
        {
            return Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NOT_APPROVED",
                "Only an approved Tax Declaration can be cancelled; a draft or pending one can be rejected instead.");
        }
        td.Status = WorkflowStatus.Cancelled;
        td.CancelledAt = clock.UtcNow;
        td.CancelledBy = currentUser.AppUserId;
        td.CancellationReason = reason;
        currentUser.Reason = reason;
        await db.SaveChangesAsync(cancellationToken);
        return Result.Success((await MapToDto(id, cancellationToken))!);
    }

    public async Task<Result<IReadOnlyList<TaxDeclarationAnnotationDto>>> ListAnnotationsAsync(Guid id, CancellationToken cancellationToken = default)
    {
        if (!await db.TaxDeclarations.AnyAsync(x => x.Id == id, cancellationToken))
        {
            return Result.Failure<IReadOnlyList<TaxDeclarationAnnotationDto>>("TAX_DECLARATION_NOT_FOUND", "No Tax Declaration was found with the given id.");
        }
        var rows = await db.TaxDeclarationAnnotations.Include(x => x.AnnotationType)
            .Where(x => x.TaxDeclarationId == id)
            .OrderBy(x => x.LiftedAt != null).ThenByDescending(x => x.EffectiveDate).ThenByDescending(x => x.CreatedAt)
            .ToListAsync(cancellationToken);
        return Result.Success<IReadOnlyList<TaxDeclarationAnnotationDto>>(rows.Select(ToDto).ToList());
    }

    public async Task<Result<TaxDeclarationAnnotationDto>> AddAnnotationAsync(Guid id, AddTaxDeclarationAnnotationRequest request, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Text) || request.Text.Length > 2000
            || request.ReferenceNumber?.Length > 100 || request.EffectiveDate == default)
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("VALIDATION_FAILED",
                "text is required (max 2000), referenceNumber max 100, effectiveDate is required.");
        }
        var td = await db.TaxDeclarations.FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (td is null)
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("TAX_DECLARATION_NOT_FOUND", "No Tax Declaration was found with the given id.");
        }
        if (td.Status is WorkflowStatus.Cancelled or WorkflowStatus.Voided or WorkflowStatus.Rejected)
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("TAX_DECLARATION_NOT_ANNOTATABLE", $"A {td.Status} Tax Declaration cannot be annotated.");
        }
        if (!await db.AnnotationTypes.AnyAsync(x => x.Id == request.AnnotationTypeId && x.IsActive, cancellationToken))
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("ANNOTATION_TYPE_NOT_FOUND", "The specified annotation type does not exist or is inactive.");
        }
        var annotation = new TaxDeclarationAnnotation
        {
            TaxDeclarationId = id, AnnotationTypeId = request.AnnotationTypeId, Text = request.Text.Trim(),
            ReferenceNumber = string.IsNullOrWhiteSpace(request.ReferenceNumber) ? null : request.ReferenceNumber.Trim(),
            ReferenceDate = request.ReferenceDate, EffectiveDate = request.EffectiveDate,
        };
        db.TaxDeclarationAnnotations.Add(annotation);
        await db.SaveChangesAsync(cancellationToken);
        await db.TaxDeclarationAnnotations.Entry(annotation).Reference(x => x.AnnotationType).LoadAsync(cancellationToken);
        return Result.Success(ToDto(annotation));
    }

    public async Task<Result<TaxDeclarationAnnotationDto>> LiftAnnotationAsync(Guid annotationId, LiftTaxDeclarationAnnotationRequest request, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Reason) || request.Reason.Length > 1000 || request.Reference?.Length > 100)
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("VALIDATION_FAILED", "A reason is required (max 1000); reference max 100.");
        }
        var annotation = await db.TaxDeclarationAnnotations.Include(x => x.AnnotationType).FirstOrDefaultAsync(x => x.Id == annotationId, cancellationToken);
        if (annotation is null)
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("ANNOTATION_NOT_FOUND", "No annotation was found with the given id.");
        }
        if (annotation.LiftedAt is not null)
        {
            return Result.Failure<TaxDeclarationAnnotationDto>("ANNOTATION_ALREADY_LIFTED", "This annotation has already been lifted.");
        }
        annotation.LiftedAt = clock.UtcNow;
        annotation.LiftedBy = currentUser.AppUserId;
        annotation.LiftReason = request.Reason;
        annotation.LiftReference = string.IsNullOrWhiteSpace(request.Reference) ? null : request.Reference.Trim();
        currentUser.Reason = request.Reason;
        await db.SaveChangesAsync(cancellationToken);
        return Result.Success(ToDto(annotation));
    }

    private static Result<TaxDeclarationDto> InTransaction() =>
        Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_IN_TRANSACTION",
            "This Tax Declaration belongs to a property transaction; it is submitted and approved with the transaction.");

    private static Result<TaxDeclarationDto> NotFound() =>
        Result.Failure<TaxDeclarationDto>("TAX_DECLARATION_NOT_FOUND", "No Tax Declaration was found with the given id.");

    private static TaxDeclarationAnnotationDto ToDto(TaxDeclarationAnnotation a) => new(
        a.Id, a.TaxDeclarationId, a.AnnotationTypeId, a.AnnotationType!.Code, a.AnnotationType.Name, a.Text, a.ReferenceNumber,
        a.ReferenceDate, a.EffectiveDate, a.CreatedAt, a.CreatedBy, a.LiftedAt, a.LiftedBy, a.LiftReason, a.LiftReference);

    private static IQueryable<TaxDeclaration> IncludeReferences(IQueryable<TaxDeclaration> query) => query
        .Include(td => td.Classification)
        .Include(td => td.ActualUse)
        .Include(td => td.Annotations)
        .Include(td => td.Assessment);

    private TaxDeclarationDto ProjectToDto(TaxDeclaration td) => new(
        td.Id,
        td.RpuId,
        td.PropertyId,
        td.TaxDeclarationNumber,
        td.RevisionNumber,
        td.EffectivityDate,
        td.Taxability,
        td.ClassificationId,
        td.Classification!.Name,
        td.ActualUseId,
        td.ActualUse!.Name,
        td.SubClassificationId,
        td.AssessmentYear,
        td.Status,
        td.PreviousTaxDeclarationId,
        td.Remarks,
        td.CreatedAt,
        td.CreatedBy,
        td.ApprovedBy,
        td.ApprovedAt,
        td.CancelledAt,
        td.CancellationReason,
        td.SupersededByTaxDeclarationId,
        td.Annotations.Count(a => a.LiftedAt == null),
        td.PropertyTransactionId,
        td.AssessmentId,
        FaasNumber(td));

    /// <summary>A TD is a FAAS once it declares an assessment; its number follows <see cref="FaasOptions.NumberSource"/>.</summary>
    private string? FaasNumber(TaxDeclaration td) => td.AssessmentId is null
        ? null
        : faas.Value.NumberSource == FaasNumberSource.TaxDeclaration ? td.TaxDeclarationNumber : td.Assessment?.FaasNumber;
}
